name: build

on:
  push:
    branches:
    # tags-ignore:
    #   - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: false
        id: go

      - name: checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: build
        run: |
          make build
          build/disconter -v
          build/disconter --help
